import sys
import os
import unittest
__dir__ = os.path.dirname(__file__)
sys.path.append(os.path.join(__dir__, '../..'))
import nullege

sample1 =   {'file': 'releases/0.9.6/topographica/examples/perrinet_retina_pynest.py',
             'lines': ['32', '45'],
             'nullege_file': 'http://nullege.com/rawsrc/src%40t%40o%40topographica-HEAD%40releases%400.9.6%40topographica%40examples%40perrinet_retina_pynest.py',
             'project': 'topographica',
             'repository': 'https://topographica.svn.sourceforge.net/svnroot/topographica'}

samples_bytearray = {'samples': [{'repository': 'http://pypi.python.org/packages/source/p/pysox/pysox-0.3.6.alpha.tar.gz', 'file': 'examples/mtest.py', 'lines': ['20', '22', '25', '27', '32', '37', '40', '42', '47'], 'nullege_file': 'http://nullege.com/rawsrc/src%40p%40y%40pysox-0.3.6.alpha%40examples%40mtest.py', 'project': 'pysox'}, {'repository': 'http://pypi.python.org/packages/source/p/pysox/pysox-0.3.6.alpha.tar.gz', 'file': 'examples/test.py', 'lines': ['49'], 'nullege_file': 'http://nullege.com/rawsrc/src%40p%40y%40pysox-0.3.6.alpha%40examples%40test.py', 'project': 'pysox'}, {'repository': 'http://pypi.python.org/packages/source/c/chai/chai-0.2.2.tar.gz', 'file': 'tests/sample_test.py', 'lines': ['164'], 'nullege_file': 'http://nullege.com/rawsrc/src%40c%40h%40chai-0.2.2%40tests%40sample_test.py', 'project': 'chai'}, {'repository': 'http://pypi.python.org/packages/source/g/ginsfsm/ginsfsm-0.4.2.tar.gz', 'file': 'ginsfsm/utils.py', 'lines': ['7', '15'], 'nullege_file': 'http://nullege.com/rawsrc/src%40g%40i%40ginsfsm-0.4.2%40ginsfsm%40utils.py', 'project': 'ginsfsm'}, {'repository': 'git://github.com/Evgenus/protocyt.git', 'file': 'protocyt/examples/benchmark/main.py', 'lines': ['49', '61', '84'], 'nullege_file': 'http://nullege.com/rawsrc/src%40p%40r%40protocyt-HEAD%40protocyt%40examples%40benchmark%40main.py', 'project': 'protocyt'}, {'repository': 'http://pypi.python.org/packages/source/p/protocyt/protocyt-0.1.4.zip', 'file': 'protocyt/examples/benchmark/main.py', 'lines': ['49', '61', '84'], 'nullege_file': 'http://nullege.com/rawsrc/src%40p%40r%40protocyt-0.1.4%40protocyt%40examples%40benchmark%40main.py', 'project': 'protocyt'}, {'repository': 'git://github.com/Evgenus/protocyt.git', 'file': 'protocyt/examples/metaprotocol/main.py', 'lines': ['19'], 'nullege_file': 'http://nullege.com/rawsrc/src%40p%40r%40protocyt-HEAD%40protocyt%40examples%40metaprotocol%40main.py', 'project': 'protocyt'}, {'repository': 'http://pypi.python.org/packages/source/p/protocyt/protocyt-0.1.4.zip', 'file': 'protocyt/examples/metaprotocol/main.py', 'lines': ['19'], 'nullege_file': 'http://nullege.com/rawsrc/src%40p%40r%40protocyt-0.1.4%40protocyt%40examples%40metaprotocol%40main.py', 'project': 'protocyt'}, {'repository': 'http://pypi.python.org/packages/source/t/tlslite/tlslite-0.4.4.tar.gz', 'file': 'tlslite/messages.py', 'lines': ['106', '107', '114', '126', '130', '144', '238', '239', '300', '304', '304', '434', '440', '519', '572', '630', '637', '662'], 'nullege_file': 'http://nullege.com/rawsrc/src%40t%40l%40tlslite-0.4.4%40tlslite%40messages.py', 'project': 'tlslite'}, {'repository': 'http://pypi.python.org/packages/source/t/tlslite/tlslite-0.4.4.tar.gz', 'file': 'tlslite/utils/compat.py', 'lines': ['30', '30', '37', '37', '72', '79'], 'nullege_file': 'http://nullege.com/rawsrc/src%40t%40l%40tlslite-0.4.4%40tlslite%40utils%40compat.py', 'project': 'tlslite'}], 'name': 'bytearray'}

